version: "3.1"
services:

  stormy_ginsberg:
    build: . 
    # ---------------
    # Comment these two lines out
    # after the first run, when the 
    # api keys are all set up.
    stdin_open: true
    tty: true
    # ---------------
    volumes:
      - "./bot/apikeys.py:/ginsberg/bot/apikeys.py"
      - "./bot/keys:/ginsberg/bot/keys"

